services:
  - type: web
    name: flow-estate-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.10.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EVOLUTION_API_URL
        sync: false
      - key: EVOLUTION_API_TOKEN
        sync: false

